apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260613-145125-cj4d6x8gfzzj-service
spec:
  selector:
    app: enterprise-system-20260613-145125-cj4d6x8gfzzj
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
